=== peggica/ist2021/proizvodi.dtd
<!ELEMENT proizvodi (proizvod+)>
<!ELEMENT proizvod (cena,tekstoglasa,oznake,akcije?)> 
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekstoglasa (#PCDATA)>
<!ELEMENT oznake (oznaka+)>
<!ELEMENT oznaka (#PCDATA)>
<!ELEMENT akcije (akcija+)>
<!ELEMENT akcija (cena, datumisteka)>
<!ELEMENT datumisteka (#PCDATA)>

<!ATTLIST proizvod kategorija (laptopovi|monitori|stolice|stolovi) #REQUIRED>
<!ATTLIST cena valuta CDATA "din">

=== peggica/ist2021/proizvodi.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE proizvodi SYSTEM "proizvodi.dtd">
<proizvodi>
    <proizvod kategorija="laptopovi">
        <cena>155500</cena>
        <tekstoglasa>Lenovo Legion Y530-15ICH 81FV00VQYA</tekstoglasa>
        <oznake>
            <oznaka>Lenovo</oznaka>
            <oznaka>Legion</oznaka>
            <oznaka>laptop</oznaka>
        </oznake>
        <akcije>
            <akcija>
                <cena>120000</cena>
                <datumisteka>30-04-2021</datumisteka>
            </akcija>
        </akcije>
    </proizvod>
    <proizvod kategorija="monitori">
        <cena valuta="eur">300</cena>
        <tekstoglasa>ASUS VZ279HE 90LM02X0-B01470</tekstoglasa>
        <oznake>
            <oznaka>ASUS</oznaka>
            <oznaka>monitor</oznaka>
        </oznake>
        <akcije>
            <akcija>
                <cena valuta="eur">220</cena>
                <datumisteka>28-04-2021</datumisteka>
            </akcija>
        </akcije>
    </proizvod>
    <proizvod kategorija="stolovi">
        <cena>16650</cena>
        <tekstoglasa>Radni sto NET106 MT931</tekstoglasa>
        <oznake>
            <oznaka>Radni</oznaka>
            <oznaka>sto</oznaka>
        </oznake>
        <akcije>
            <akcija>
                <cena>10490</cena>
                <datumisteka>30-04-2021</datumisteka>
            </akcija>
            <akcija>
                <cena>11000</cena>
                <datumisteka>15-05-2021</datumisteka>
            </akcija>
        </akcije>
    </proizvod>
    <proizvod kategorija="stolice">
        <cena>9300</cena>
        <tekstoglasa>Dečija kompjuter stolica FY-0738</tekstoglasa>
        <oznake>
            <oznaka>dečija</oznaka>
            <oznaka>kompjuter</oznaka>
            <oznaka>stolica</oznaka>
        </oznake>
    </proizvod>
</proizvodi>
